// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthService.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioPapel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Ativo = true,
                            Email = "admin@example.com",
                            Name = "Admin",
                            Senha = "$2a$11$wsHii5Yy26cQv2vhAsZJmuu2Is/dtyU9OKpwmbxhp73BvYjhK26my",
                            UsuarioPapel = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Ativo = true,
                            Email = "registrador@example.com",
                            Name = "Registrador",
                            Senha = "$2a$11$SOlOp.7wMedXA.mb6K0kzup9BlJVzKOB4KIlnGjObrRxeXS745kZa",
                            UsuarioPapel = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Ativo = true,
                            Email = "consulta@example.com",
                            Name = "Consulta",
                            Senha = "$2a$11$Evh01g.08S7I/dteTfdLB.P.jAb.DgWU6cSMMCHbMCYHqE/06mruG",
                            UsuarioPapel = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
