// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RegistrosService.Migrations
{
    [DbContext(typeof(RegistrosDbContext))]
    [Migration("20260621201217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Registro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("CriadoPorNome")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DataEntrada")
                        .HasColumnType("date");

                    b.Property<string>("NomeApresentante")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Registros");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AtualizadoEm = new DateTime(2026, 6, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            CpfCnpj = "42591651000143",
                            CriadoEm = new DateTime(2026, 6, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = new Guid("00000000-0000-0000-0000-000000000001"),
                            CriadoPorNome = "Admin",
                            DataEntrada = new DateOnly(2026, 6, 20),
                            NomeApresentante = "Empresa Contrato LTDA",
                            Observacoes = "Registro seed contrato",
                            Status = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AtualizadoEm = new DateTime(2026, 6, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            CpfCnpj = "42591651000143",
                            CriadoEm = new DateTime(2026, 6, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = new Guid("00000000-0000-0000-0000-000000000002"),
                            CriadoPorNome = "Registrador",
                            DataEntrada = new DateOnly(2026, 6, 19),
                            NomeApresentante = "João da Silva",
                            Observacoes = "Registro seed procuração",
                            Status = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AtualizadoEm = new DateTime(2026, 6, 18, 8, 0, 0, 0, DateTimeKind.Utc),
                            CpfCnpj = "42591651000143",
                            CriadoEm = new DateTime(2026, 6, 18, 8, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = new Guid("00000000-0000-0000-0000-000000000003"),
                            CriadoPorNome = "Consulta",
                            DataEntrada = new DateOnly(2026, 6, 18),
                            NomeApresentante = "Empresa Notificação SA",
                            Observacoes = "Registro seed notificação",
                            Status = 0,
                            Tipo = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
